### PR TITLE
add aur packaging status

### PR DESCRIPTION
**Pull request by getchoo**
this pr will advertise the [aur package](https://aur.archlinux.org/packages/lightmaputil-git) for the project, allowing for easy install options right up front 👯

### CODE REVIEW

**Comment by treacherousfiend** [comment]
Arch linux moment

**Comment by micwoj92** [comment]
This badge shows basically no information, it's just "maintainer getchoo".
You should rather be using https://repology.org/badge/vertical-allrepos/lightmaputil.svg 
if you want to show in which repos it is. or create custom badge on shields.io

**Comment by getchoo** [comment]
@micwoj92 that was the point noob

**Comment by treacherousfiend** [comment]
I removed it because it's really not helpful at all, it just says "Maintainer: getchoo", it's just confusing

**Pull request merged**
